# Machine Learning - Practicum 2
<b>Student:</b> Justin Klein<br>
<b>Nummer:</b> 1707815

In [1]:
from perceptron import Perceptron
import random
import numpy as np
from sklearn.datasets import load_iris

## Perceptrons and Train functions
Eerst maken we de perceptrons aan met willekeurig gekozen weights. De AND perceptron heeft een learning rate van 0.1, maar de XOR niet. Dit komt omdat een beter resultaat (lagere MSE) bereikt wordt met een 0.01 learning rate bij de XOR. Als de learning rate niet 0.01 is gaat de MSE omhoog naar 0.5.

In [2]:
p1 = Perceptron("AND", [4, 9], 0, 0.1)
p2 = Perceptron("XOR", [3, 4], 0, 0.01)

Hier maken we een lijst met de mogelijke combinaties van inputs voor de perceptrons. Ook hebben we hier een kleine functie die het trainproces start en de informatie van de perceptrons print (weights, bias, learning_rate, etc.). <b>Zie perceptron.py voor meer informatie over de werking.</b>

In [3]:
pos_2x = [[1, 1], [1, 0], [0, 1], [0, 0]]

In [4]:
def train_perceptron(p, inputs, expected, num_of_epochs):
    print(f"{p}\n")
    p.train(inputs, expected, num_of_epochs)
    print(f"\n{p}")

### Training Perceptrons (AND & XOR)
Hier trainen we en testen we de eerste twee cases, de AND en XOR. We geven dus de perceptron, inputs, verwachte waardes en hoeveelheid epochs mee.
We kunnen zien welke outputs correct zijn in vergelijking met de verwactte waardes en de total loss die daar uit volgt.

In [5]:
train_perceptron(p1, pos_2x, [1, 0, 0, 0], 40) # AND

Perceptron | Type: 'AND' | Weights: '[4, 9]' | Bias: '0' | Learning Rate: '0.1'

------------------ Epoch: 1 ------------------
[AND] | Input: [1, 1] | Output: 1 | Correct: True
[AND] | Input: [1, 0] | Output: 1 | Correct: False
[AND] | Input: [0, 1] | Output: 1 | Correct: False
[AND] | Input: [0, 0] | Output: 0 | Correct: True
[AND] | Total loss (MSE): 0.5

------------------ Epoch: 2 ------------------
[AND] | Input: [1, 1] | Output: 1 | Correct: True
[AND] | Input: [1, 0] | Output: 1 | Correct: False
[AND] | Input: [0, 1] | Output: 1 | Correct: False
[AND] | Input: [0, 0] | Output: 0 | Correct: True
[AND] | Total loss (MSE): 0.5

------------------ Epoch: 3 ------------------
[AND] | Input: [1, 1] | Output: 1 | Correct: True
[AND] | Input: [1, 0] | Output: 1 | Correct: False
[AND] | Input: [0, 1] | Output: 1 | Correct: False
[AND] | Input: [0, 0] | Output: 0 | Correct: True
[AND] | Total loss (MSE): 0.5

------------------ Epoch: 4 ------------------
[AND] | Input: [1, 1] | Output: 

De XOR kan helaas nooit een total loss van 0.0 bereiken zoals de AND. Dit is ook getest met 100 epochs en nog komt de XOR total loss niet lager dan 0.25.

In [6]:
train_perceptron(p2, pos_2x, [0, 1, 1, 0], 10) # XOR

Perceptron | Type: 'XOR' | Weights: '[3, 4]' | Bias: '0' | Learning Rate: '0.01'

------------------ Epoch: 1 ------------------
[XOR] | Input: [1, 1] | Output: 1 | Correct: False
[XOR] | Input: [1, 0] | Output: 1 | Correct: True
[XOR] | Input: [0, 1] | Output: 1 | Correct: True
[XOR] | Input: [0, 0] | Output: 0 | Correct: True
[XOR] | Total loss (MSE): 0.25

------------------ Epoch: 2 ------------------
[XOR] | Input: [1, 1] | Output: 1 | Correct: False
[XOR] | Input: [1, 0] | Output: 1 | Correct: True
[XOR] | Input: [0, 1] | Output: 1 | Correct: True
[XOR] | Input: [0, 0] | Output: 0 | Correct: True
[XOR] | Total loss (MSE): 0.25

------------------ Epoch: 3 ------------------
[XOR] | Input: [1, 1] | Output: 1 | Correct: False
[XOR] | Input: [1, 0] | Output: 1 | Correct: True
[XOR] | Input: [0, 1] | Output: 1 | Correct: True
[XOR] | Input: [0, 0] | Output: 0 | Correct: True
[XOR] | Total loss (MSE): 0.25

------------------ Epoch: 4 ------------------
[XOR] | Input: [1, 1] | Output:

## IRIS Dataset
Dit is de derde case waarin we naar de IRIS dataset kijken en hier een perceptron op gaan toepassen.
<br>Eerst laden we de data in (zowel de data als de verwachte waardes).

In [7]:
iris = load_iris()
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [8]:
X = iris.data
print(X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

Nu we de data hebben ingeladen kijken we naar de target. De target bevat echter ook de targets van de Virginica, dit moeten we dus wegfilteren zodat we alleen de Setosa en Versicolor overhouden.

In [9]:
y = iris.target
print(y)

y = y[y != 2] # We only use Setosa and Versicolor.
print(y)

X = X[:len(y)] # Make data and target arrays equal in length.

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


## Random parameters
Zoals in de opdracht aangegeven genereren we hier willekeurige parameters voor de IRIS perceptron.

In [10]:
random.seed(1707815)

weights = [random.random(), random.random(), random.random(), random.random()]
bias = random.random()
lr = random.random()

print(f"Weights: {weights}")
print(f"Bias: {bias}")
print(f"Learning Rate: {lr}")

Weights: [0.07494665954220647, 0.9254040556559965, 0.15307540459956503, 0.526336766854629]
Bias: 0.27062105629448796
Learning Rate: 0.4627047423224553


## IRIS Perceptron en training - IRIS I
Hier maken we een perceptron met de ingevoerde willekeurige waardes. Vervolgens trainen we deze perceptron met de X data en y targets. Ik had voor 10 epochs gekozen maar hij bleek niet meer dan 4 nodig te hebben om een total loss van 0 te bereiken. Aan het einde van het trainen zien we de ge-update parameters die de perceptron nu heeft.

In [11]:
p3 = Perceptron("IRIS", weights, bias, lr)
train_perceptron(p3, X, y, 10)

Perceptron | Type: 'IRIS' | Weights: '[0.07494665954220647, 0.9254040556559965, 0.15307540459956503, 0.526336766854629]' | Bias: '0.27062105629448796' | Learning Rate: '0.4627047423224553'

------------------ Epoch: 1 ------------------
[IRIS] | Input: [5.1 3.5 1.4 0.2] | Output: 1 | Correct: False
[IRIS] | Input: [4.9 3.  1.4 0.2] | Output: 0 | Correct: True
[IRIS] | Input: [4.7 3.2 1.3 0.2] | Output: 0 | Correct: True
[IRIS] | Input: [4.6 3.1 1.5 0.2] | Output: 0 | Correct: True
[IRIS] | Input: [5.  3.6 1.4 0.2] | Output: 0 | Correct: True
[IRIS] | Input: [5.4 3.9 1.7 0.4] | Output: 0 | Correct: True
[IRIS] | Input: [4.6 3.4 1.4 0.3] | Output: 0 | Correct: True
[IRIS] | Input: [5.  3.4 1.5 0.2] | Output: 0 | Correct: True
[IRIS] | Input: [4.4 2.9 1.4 0.2] | Output: 0 | Correct: True
[IRIS] | Input: [4.9 3.1 1.5 0.1] | Output: 0 | Correct: True
[IRIS] | Input: [5.4 3.7 1.5 0.2] | Output: 0 | Correct: True
[IRIS] | Input: [4.8 3.4 1.6 0.2] | Output: 0 | Correct: True
[IRIS] | Input: [4

[IRIS] | Input: [6.7 3.  5.  1.7] | Output: 1 | Correct: True
[IRIS] | Input: [6.  2.9 4.5 1.5] | Output: 1 | Correct: True
[IRIS] | Input: [5.7 2.6 3.5 1. ] | Output: 1 | Correct: True
[IRIS] | Input: [5.5 2.4 3.8 1.1] | Output: 1 | Correct: True
[IRIS] | Input: [5.5 2.4 3.7 1. ] | Output: 1 | Correct: True
[IRIS] | Input: [5.8 2.7 3.9 1.2] | Output: 1 | Correct: True
[IRIS] | Input: [6.  2.7 5.1 1.6] | Output: 1 | Correct: True
[IRIS] | Input: [5.4 3.  4.5 1.5] | Output: 1 | Correct: True
[IRIS] | Input: [6.  3.4 4.5 1.6] | Output: 1 | Correct: True
[IRIS] | Input: [6.7 3.1 4.7 1.5] | Output: 1 | Correct: True
[IRIS] | Input: [6.3 2.3 4.4 1.3] | Output: 1 | Correct: True
[IRIS] | Input: [5.6 3.  4.1 1.3] | Output: 1 | Correct: True
[IRIS] | Input: [5.5 2.5 4.  1.3] | Output: 1 | Correct: True
[IRIS] | Input: [5.5 2.6 4.4 1.2] | Output: 1 | Correct: True
[IRIS] | Input: [6.1 3.  4.6 1.4] | Output: 1 | Correct: True
[IRIS] | Input: [5.8 2.6 4.  1.2] | Output: 1 | Correct: True
[IRIS] |

[IRIS] | Input: [5.1 3.7 1.5 0.4] | Output: 0 | Correct: True
[IRIS] | Input: [4.6 3.6 1.  0.2] | Output: 0 | Correct: True
[IRIS] | Input: [5.1 3.3 1.7 0.5] | Output: 0 | Correct: True
[IRIS] | Input: [4.8 3.4 1.9 0.2] | Output: 0 | Correct: True
[IRIS] | Input: [5.  3.  1.6 0.2] | Output: 0 | Correct: True
[IRIS] | Input: [5.  3.4 1.6 0.4] | Output: 0 | Correct: True
[IRIS] | Input: [5.2 3.5 1.5 0.2] | Output: 0 | Correct: True
[IRIS] | Input: [5.2 3.4 1.4 0.2] | Output: 0 | Correct: True
[IRIS] | Input: [4.7 3.2 1.6 0.2] | Output: 0 | Correct: True
[IRIS] | Input: [4.8 3.1 1.6 0.2] | Output: 0 | Correct: True
[IRIS] | Input: [5.4 3.4 1.5 0.4] | Output: 0 | Correct: True
[IRIS] | Input: [5.2 4.1 1.5 0.1] | Output: 0 | Correct: True
[IRIS] | Input: [5.5 4.2 1.4 0.2] | Output: 0 | Correct: True
[IRIS] | Input: [4.9 3.1 1.5 0.2] | Output: 0 | Correct: True
[IRIS] | Input: [5.  3.2 1.2 0.2] | Output: 0 | Correct: True
[IRIS] | Input: [5.5 3.5 1.3 0.2] | Output: 0 | Correct: True
[IRIS] |

## IRIS Perceptron en training - IRIS II
Deze testcase is echter lastiger. De target array maakt namelijk gebruik van 0, 1 en 2. En omdat we alleen een 0 of 1 krijgen is het lastig om de Verginica te trainen (dit wordt aangegeven als 2 namelijk). Om dit te omzeilen kan ik de nul waardes weghalen, de 1 veranderen in de 0 en de 2 naar een 1. Zo kunnen we ook de X array aanpassen zodat we de records die niet Versicolor of Verginica zijn weghalen.

In [12]:
X = iris.data
y = iris.target

count_y = np.bincount(y)

print(y)
y = y[y != 0] # We only use Versicolor and Verginica.
y[y == 1] = 0
y[y == 2] = 1
print(y)

X = X[count_y[0]:] # Make data and target arrays equal in length.

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


Nu de data klaar is kunnen we de perceptron redefinen en opnieuw trainen met de nieuwe data. Ik had voor 10 epochs gekozen maar hij bleek niet te veranderen na de eerste epoch dus heb ik hem op 3 epochs gelaten. Aan het einde van het trainen zien we de ge-update parameters die de perceptron nu heeft.

In [13]:
p3 = Perceptron("IRIS", weights, bias, lr)
train_perceptron(p3, X, y, 3)

Perceptron | Type: 'IRIS' | Weights: '[0.07494665954220647, 0.9254040556559965, 0.15307540459956503, 0.526336766854629]' | Bias: '0.27062105629448796' | Learning Rate: '0.4627047423224553'

------------------ Epoch: 1 ------------------
[IRIS] | Input: [7.  3.2 4.7 1.4] | Output: 1 | Correct: False
[IRIS] | Input: [6.4 3.2 4.5 1.5] | Output: 0 | Correct: True
[IRIS] | Input: [6.9 3.1 4.9 1.5] | Output: 0 | Correct: True
[IRIS] | Input: [5.5 2.3 4.  1.3] | Output: 0 | Correct: True
[IRIS] | Input: [6.5 2.8 4.6 1.5] | Output: 0 | Correct: True
[IRIS] | Input: [5.7 2.8 4.5 1.3] | Output: 0 | Correct: True
[IRIS] | Input: [6.3 3.3 4.7 1.6] | Output: 0 | Correct: True
[IRIS] | Input: [4.9 2.4 3.3 1. ] | Output: 0 | Correct: True
[IRIS] | Input: [6.6 2.9 4.6 1.3] | Output: 0 | Correct: True
[IRIS] | Input: [5.2 2.7 3.9 1.4] | Output: 0 | Correct: True
[IRIS] | Input: [5.  2.  3.5 1. ] | Output: 0 | Correct: True
[IRIS] | Input: [5.9 3.  4.2 1.5] | Output: 0 | Correct: True
[IRIS] | Input: [6

[IRIS] | Input: [6.1 3.  4.9 1.8] | Output: 1 | Correct: True
[IRIS] | Input: [6.4 2.8 5.6 2.1] | Output: 1 | Correct: True
[IRIS] | Input: [7.2 3.  5.8 1.6] | Output: 1 | Correct: True
[IRIS] | Input: [7.4 2.8 6.1 1.9] | Output: 1 | Correct: True
[IRIS] | Input: [7.9 3.8 6.4 2. ] | Output: 1 | Correct: True
[IRIS] | Input: [6.4 2.8 5.6 2.2] | Output: 1 | Correct: True
[IRIS] | Input: [6.3 2.8 5.1 1.5] | Output: 1 | Correct: True
[IRIS] | Input: [6.1 2.6 5.6 1.4] | Output: 1 | Correct: True
[IRIS] | Input: [7.7 3.  6.1 2.3] | Output: 1 | Correct: True
[IRIS] | Input: [6.3 3.4 5.6 2.4] | Output: 1 | Correct: True
[IRIS] | Input: [6.4 3.1 5.5 1.8] | Output: 1 | Correct: True
[IRIS] | Input: [6.  3.  4.8 1.8] | Output: 1 | Correct: True
[IRIS] | Input: [6.9 3.1 5.4 2.1] | Output: 1 | Correct: True
[IRIS] | Input: [6.7 3.1 5.6 2.4] | Output: 1 | Correct: True
[IRIS] | Input: [6.9 3.1 5.1 2.3] | Output: 1 | Correct: True
[IRIS] | Input: [5.8 2.7 5.1 1.9] | Output: 1 | Correct: True
[IRIS] |